services:
  node:
    container_name: npm
    build: ./requirements/node/.
    env_file:
      - .env
    volumes:
      - node_db:/app/$VOLUME_NAME
    ports:
      - "3000:3000"
    restart:
      on-failure

volumes:
  node_db:
    driver_opts:
      type: 'none'
      o: bind
      device: /goinfre/$USER/docker/volumes/srcs_node_db/_data